name: dwind
channels:
  - conda-forge
  - nrel
dependencies:
  - python=3.11
  - nrel-rex
  - pandas
  - numpy
  - sqlalchemy
  - psycopg2
  - scipy
  - matplotlib
  - seaborn
  - pip
  - pyarrow
  - pip:
    - nrel-pysam>=7.1
    - h5pyd
    - typer
    - "."
