# Book settings
# Learn more at https://jupyterbook.org/v1/customize/config.html
# Generally, check v1 of the Jupyter Book docs for more details: https://jupyterbook.org/v1/intro.html

title: dwind
author: Rob Hammond
# logo: logo.png
copyright: "2025"
only_build_toc_files: false

execute:
  execute_notebooks: auto
  timeout: -1
  merge_streams: true
  exclude_patterns:
    - _build
    - Thumbs.db
    - DS_Store
    - "**.ipynb_checkpoints"

latex:
  latex_documents:
    targetname: book.tex

bibliography:
  - references.bib

repository:
  url: https://github.com/NatlLabRockies/dwind
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  baseurl: https://natlabrockies.github.io/dwind/

sphinx:
  extra_extensions:
  - "sphinx.ext.autodoc"
  - "sphinx.ext.autosummary"
  - "sphinx.ext.napoleon"
  - 'sphinx.ext.viewcode'
  - 'sphinx_autodoc_typehints'
  language: 'python'
  autosummary_generate: true
  suppress_warnings:
    - etoc.toctree
  autodoc_default_options:
    members: true
    member-order: bysource
    undoc-members: true
    private-members: false
    # special-members: true
    # inherited-members
    # show-inheritance
    # ignore-module-all
    # imported-members: true
    # exclude-members
    # class-doc-from
    # no-value
  autodoc_typehints: description
  napoleon_use_admonition_for_notes: true
  napoleon_use_rtype: false
  nb_merge_streams: true
